# Site settings
name: Daniel Felizi
description: "back-end developer"
url: "felizi.net"

github_username:  felizi
twitter_username: danielfelizi
linkedin_username: felizi
stack_of_username: 2370031
medium_username:  felizi
blog_url: "/blog"
email: felizi.daniel@gmail.com

avatar: yes
avatar_img_path: "imgs/avatar.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty
